name: Nightly build
on:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/nightly.yml
  pull_request:
    paths:
      - .github/workflows/nightly.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!" > message.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: message.txt
